// Generated by https://quicktype.io

export interface Equipo {
  id_activo_fijo: string;
  nombre:         string;
  serie:          string;
  tipo:           string;
  fecha_compra:   string;
  fecha_baja:     string;
  estado:         string;
  tipo_propiedad: string;
  OS:             string;
  modelo:         string;
  fabricante:     string;
}
